<?php

namespace AppBundle\Repository;

/**
 * AutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorRepository extends \Doctrine\ORM\EntityRepository
{   
    public function findAutorByName()
    {
        return $this->getEntityManager()
        ->createQuery
        (
            "SELECT a FROM AppBundle:Autor a ORDER BY a.name ASC"
        )
        ->getResult();
    }
}
