AppBundle\Entity\post:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\postRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        text:
            type: text
        date:
            type: datetime
    lifecycleCallbacks: {  }
    manyToOne:
        category:
            targetEntity: category
            inversedBy: post
            joinColumn:
                name: category_id
                referencedColumnName: id
        autor:
            targetEntity: Autor
            inversedBy: post
            joinColumn:
                name: autor_id
                referencedColumnName: id
    manyToMany:
        tag:
            targetEntity: Tag
            inversedBy: post
            joinTable:
                name: searching_By_Tag
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id